sonar.organization=hellorin
sonar.projectKey=Solea
sonar.projectName=Solea

sonar.sources=src
sonar.tests=src/test
sonar.exclusions=src/test/**,src/sw.ts,src/main.tsx,public/**,dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/test/**,src/main.tsx,src/sw.ts,vite.config.ts,eslint.config.js

sonar.sourceEncoding=UTF-8
